/* Edition 21: five voices, one troublesome garden. */
'use strict';
(()=>{
 const additions={
  snickers:{
   intro:['Snickers hat sich die größte Haselnuss bis zum Schluss aufgehoben. Noch ein Schluck Tee, dann wäre sie dran gewesen. Da greift eine Pfote über den Tisch. Hasenbein steckt die Nuss ein, salutiert und tritt beim Abgang in den Napf. Snickers sieht ihm nach. Dann holt er die Kanone aus dem Schuppen. Den Tee kann er jetzt ohnehin vergessen.','Hasenbein: Die brauche ich für die Truppe.','Dann soll die Truppe sich einen Nussbaum pflanzen.'],
   plus:['Der Gartenzaun ist kaum wieder gerade, da klopft Hasenbein dagegen. Neuer Helm, neue Hasen, dieselbe beleidigte Schnauze. Snickers hat seine Kanone noch nicht weggeräumt. Das spart Zeit. Als der General seine Rede beginnt, zieht der Hamster schon die Abdeckplane herunter.','Hasenbein: Diesmal läuft es anders!','Stimmt. Diesmal weiß ich, wo du wohnst.'],
   plus2:['Endlich sitzen alle beim Essen. Nur die Sahne fehlt. Auf dem leeren Fass klebt ein Zettel: „Ausgeliehen. Ottah.“ Snickers dreht ihn um. Kein Rückgabedatum. Aus der Küche am anderen Ende des Gartens kommt ein sehr zufriedenes Schmatzen. Er nimmt den Nachtischlöffel mit. Und vorsichtshalber die Kanone.','Ottah: War die für alle?','Ja. Du bist bloß nicht alle.'],
   act1:['Hasenbein liegt zwischen den Möhren und tut so, als würde er seine Schnürsenkel binden. Zwei Hasen tragen ihn weg. Unter dem Beet geht eine Luke auf, und ein metallener Doppelgänger fährt hoch. Snickers schaut auf die dampfende Kanone. Er hatte gehofft, heute nur einen General erledigen zu müssen.','Cyber-Hasenbein: Verbesserte Ausführung. Keine bekannten Schwächen.','Die Ohren stehen immer noch oben raus.'],
   act2:['Der Cyberhase kippt um. Ein letztes Piepen, dann ist Ruhe. Snickers greift nach der Nuss, doch eine riesige Hand ist schneller. Karnil hebt sie zwischen zwei Fingern hoch und schnuppert daran. Hinter ihm bröckelt die Felswand. Offenbar kann dieser Kerl schon beim Stehen Schaden anrichten.','Karnil: WEGEN DER KLEINEN NUSS MACHST DU DEN GANZEN ÄRGER?','Für dich ist sie klein. Für mich ist das Abendessen.'],
   ottah:['Karnil hat sich endlich hingesetzt. Snickers folgt den Sahneflecken bis zu Ottah, der mitten im Vorratslager hockt. Auf jedem Topf steht sein Name. Sogar auf einem leeren. Pafti versteckt hastig einen Löffel hinter dem Rücken. Snickers stellt die Kanone auf den Tisch. Zwei Becher wandern ein Stück zur Seite.','Ottah: Wir haben nichts mehr da.','Du hast noch was am Bart.'],
   pafti:['Karnil wackelt schon, als Pafti hinter einem Stein hervorspringt. Sein Controller-Kopf blinkt. Mit einem hellen Pling bekommt das Sauferkel ein Viertel seines maximalen Lebens zurück. Snickers lässt die Kanone sinken und starrt Pafti an. Der versucht, pfeifend wieder hinter dem Stein zu verschwinden.','Pafti: Ich dachte, wir machen noch eine Runde.','Du machst gleich eine Runde um den Garten. Vor mir her.']
  },
  raffzahn:{
   intro:['Raffzahn greift nach seinem goldenen Käsekompass. Weg. Stattdessen liegt auf der Karte ein Möhrenrest. Er folgt der Krümelspur bis zum Gully, wo Hasenbein gerade feststeckt. Während zwei Soldaten am General ziehen, steckt der den Kompass tiefer in die Tasche. Raffzahn klappt sein Messer auf.','Hasenbein: Das ist kein Diebstahl. Das ist eine Kontrolle.','Dann kontrollier mal, ob du noch durch das Loch passt.'],
   plus:['Am Kanaleingang liegt frischer Käse. Dahinter steht ein Schild: „Keine Falle“. Raffzahn schaut unter den Käse. Eine Falle. Er nimmt beides mit. Um die Ecke hält Hasenbein noch die Schnur und wartet aufs Zuschlagen. Die nächste Begegnung dürfte für ihn ziemlich überraschend werden.','Hasenbein: Warum hat das nicht geklappt?','Du hast „Falle“ auf die Falle geschrieben.'],
   plus2:['Ottah hat eine Käsekammer, die angeblich niemand findet. Raffzahn riecht sie schon vom Gartenzaun aus. Vor der Tür steht Pafti mit einer Wäscheklammer auf der Nase. Drinnen wird geschmatzt. Raffzahn legt sein Ohr an die Wand, nickt und sucht den nächsten Abfluss.','Ottah: Hier kommt keine Ratte rein!','Dein Rohr sagt was anderes.'],
   act1:['Hasenbein verliert seinen Helm und gleich danach den Kampf. Der Käsekompass zeigt trotzdem weiter nach unten. Raffzahn hebt den Gullydeckel an. Im Labor darunter wartet Cyber-Hasenbein zwischen Kabeln und Käseresten. Er hat versucht, den Geruch mit einem Duftbaum zu verstecken.','Cyber-Hasenbein: Du kannst mich nicht aufspüren.','Wunderbaum mit Cheddar. Gewagt.'],
   act2:['Hinter dem kaputten Cyberhasen führt eine Schleifspur zum Schrottplatz. Dort sitzt Karnil auf einer Kiste. Aus dem Deckel hängt Raffzahns Kompasskette. Karnil rutscht hastig darüber, worauf die Kiste knackt. Raffzahn hält ihm wortlos die Pfote hin.','Karnil: ICH HABE NICHTS.','Dann heb doch mal den Hintern.'],
   ottah:['Der Kompass ist zurück. Er zeigt direkt auf Ottahs letzten Käsevorrat. Das Schloss an der Tür ist teuer; die Wand daneben hat ein faustgroßes Loch. Raffzahn schlüpft hindurch und landet neben Paftis Stiefeln. Der schreit. Ottah verschluckt sich. So viel zum unbemerkten Einstieg.','Ottah: Du hättest klopfen können!','Du hättest aufmachen können. Wir sparen beide Zeit.'],
   pafti:['Raffzahn hat Karnil schon als erledigt durchgestrichen. Da drückt Pafti auf seinen Controller-Kopf und heilt ihn um ein Viertel seines maximalen Lebens. Der Felsbrocken steht wieder. Raffzahn zieht den Stift, streicht den Strich durch und zeigt damit auf Pafti.','Pafti: Jetzt darfst du noch mal!','Ja. Dich zuerst.']
  },
  krustenbraten:{
   intro:['Kornelius will gerade die Kruste aus dem Ofen holen. Auf dem Tresen fehlt sein Rezept. Durchs Fenster sieht er Hasenbein damit davonlaufen, während der General das Blatt verkehrt herum liest. Kornelius nimmt die Pfanne vom Haken. Hinter ihm klingelt die Eieruhr. Das wird wohl ein etwas dunklerer Braten.','Hasenbein: Das Rezept gehört jetzt der Armee!','Dann lies wenigstens „Salz“ richtig rum, du Löffel.'],
   plus:['Hasenbein hat Kornelius eine Kostprobe geschickt. Sie ist grau, steinhart und enthält eine Schraube. „Nach deinem Rezept“, steht auf dem Zettel. Kornelius legt das Stück vorsichtig ab. Es schlägt ein Loch in den Teller. Er nimmt die Pfanne und zieht die Backstubentür hinter sich zu.','Hasenbein: Na? Schmeckt wie bei dir, oder?','Mein Essen kann man kauen.'],
   plus2:['Die Sahne für den Festbraten ist weg. Kornelius folgt den klebrigen Spuren bis zu Ottahs Küche. Pafti sitzt vor der Tür und schleckt den Messbecher aus. Auf die Frage nach der Sahne schüttelt er den Kopf. Dabei läuft ihm ein Tropfen übers Kinn. Kornelius schiebt den Ofenwagen heran.','Ottah: Wir haben nur probiert.','Sechs Fässer? Mit was, einer Schaufel?'],
   act1:['Hasenbein hat das Rezept nicht mehr. Unter dem Herd rattert eine Maschine und druckt Kopien aus. Cyber-Hasenbein liest sie laut vor. Bei „eine Prise Salz“ schüttet er einen ganzen Eimer in den Topf. Kornelius atmet langsam durch die Nase. Die Pfanne hält er jetzt mit beiden Händen.','Cyber-Hasenbein: Geschmackstest abgeschlossen. Hervorragend.','Du hast ja auch keine Zunge.'],
   act2:['Der Drucker schweigt, doch aus der Räucherei quillt noch Rauch. Karnil hat das Originalrezept vor sich und einen schwarzen Klumpen auf dem Teller. Er bietet Kornelius ein Stück an. Der Koch sticht mit der Gabel hinein. Eine Zinke bricht ab. Karnil kaut weiter.','Karnil: IN DER MITTE IST ES NOCH WEICH.','Das ist dein Teller.'],
   ottah:['Kornelius hat sein Rezept, aber Ottah sitzt auf dem letzten freien Herd. Pafti hält den Topfdeckel wie einen Schild vor sich. Der Koch schiebt seinen Ofenwagen dazwischen und prüft die Temperatur. Als es anfängt zu knacken, steht Ottah sehr schnell auf.','Ottah: Wir wollten gerade zumachen.','Gut. Dann stehen wir uns nicht mehr im Weg.'],
   pafti:['Karnil ist fast fertig, da gönnt ihm Pafti noch ein Viertel seines maximalen Lebens. Der große Kerl steht wieder auf und verlangt Nachschlag. Kornelius wischt die Pfanne an der Schürze ab. Für einen Augenblick sieht es aus, als würde er zählen, wie viele Portionen Pafti selbst wohl abgibt.','Pafti: Aufgewärmt schmeckt es doch oft besser.','Komm her. Prüfen wir.']
  },
  slanny:{
   intro:['Slanny soll wieder Wache stehen, während Hasenbein Mittagsschlaf hält. Er sagt Nein. Der General reißt ihm das Freiheitsabzeichen ab und stapft davon. Slanny wartet, bis er um die Ecke ist. Dann holt er die Möhrenklinge aus dem Gürtel. Seinen letzten Arbeitstag hatte er sich ruhiger vorgestellt.','Hasenbein: Du bleibst gefälligst, wo du bist!','Klar. Sobald ich mein Abzeichen wiederhabe.'],
   plus:['Hasenbein ist zurück. Seine neue Truppe steht stramm, bis einer fragt, ob es auch eine Pause gibt. Der General brüllt. Slanny lehnt am Zaun und winkt die Rekruten zu sich. Zwei kommen sofort. Der Rest wartet noch auf die Antwort zur Pause.','Hasenbein: Hör auf, meine Leute abzuwerben!','Dann gib ihnen mal was zu essen.'],
   plus2:['Am Tor der Wurzelkatakomben drängen sich Hasen, die nach Hause wollen. Ottah hat abgeschlossen und sich auf den Schlüssel gesetzt. Slanny schiebt sich nach vorn. Neben seinem Fuß bricht eine Ranke durch den Stein. Pafti zieht seinen Stuhl ein gutes Stück zurück.','Ottah: Ohne Schlüssel kommt hier keiner raus.','Die Pflanze kann offenbar nicht lesen.'],
   act1:['Hasenbein ist geschlagen, aber Slannys Abzeichen hängt im Labor an einer Antenne. Cyber-Hasenbein nennt es einen Sender. Slanny nennt es sein Abzeichen. Der Blechhase fordert ihn auf, stillzustehen. Slanny wirft die Möhrenklinge, bevor der Satz zu Ende ist.','Cyber-Hasenbein: Bewegung verboten.','Dann versuch mal, das Ding zu fangen.'],
   act2:['Slanny steckt sein Abzeichen wieder an. Da bebt die Lichtung. Karnil hat den Weg mit Geröll zugeschüttet; dahinter rufen die Hasen nach Hilfe. Slanny zieht den ersten über einen Stein und drückt ihm die Klinge in die Pfote, bis alle frei sind. Erst dann dreht er sich zum Sauferkel um.','Karnil: DIE BLEIBEN HIER!','Einer hat noch deine Fußmatte. Sonst sind alle fertig.'],
   ottah:['Vor dem letzten Ausgang wartet Ottah. Drei Ketten, zwei Vorhängeschlösser und Pafti sollen reichen, um die Hasen aufzuhalten. Slanny schaut zu den Wurzeln unter dem Pflaster. Die anderen treten zurück. Nur Pafti bleibt stehen, weil sein Schnürsenkel am Tor hängt.','Ottah: Das hält eine Ewigkeit!','Pafti würde gern vorher losgebunden werden.'],
   pafti:['Slanny fängt seine Klinge auf. Hinter ihm jubeln schon die Hasen, doch Pafti drückt noch schnell einen Knopf: Karnil erhält ein Viertel seines maximalen Lebens zurück. Das Jubeln hört auf. Slanny schaut Pafti an. Der senkt die Hände, aber sein Controller-Kopf blinkt munter weiter.','Pafti: War ich nicht.','Du leuchtest noch.']
  },
  koettitroeter:{
   intro:['Der Köttitröter holt Luft für sein Solo. Es kommt nur ein dünnes Pfffft. Hasenbein steht neben der Bühne und hält das goldene Mundstück hoch. Er will endlich seine Mittagsruhe. Der Troll nimmt das Ersatzstück aus der Tasche. Das kratzt ein bisschen. Heute passt das ganz gut.','Hasenbein: Jetzt ist hier Ruhe!','Warte. Das Ersatzstück ist lauter.'],
   plus:['Die Hasen stehen wieder vor der Bühne. Diesmal mit Gehörschutz. Einer hat sich zwei Brötchen an die Ohren gebunden. Der Köttitröter zeigt darauf und lacht so lange, dass Hasenbein ungeduldig mit dem Fuß stampft. Dann setzt der Troll die Trompete an.','Hasenbein: Wir sind vorbereitet!','Der da ist bloß zum Frühstück gekommen.'],
   plus2:['Ottah hat den Konzertsaal übernommen. Pafti spielt drei Töne immer wieder, und Ottah nennt das eine Zugabe. Im Publikum sitzen zwei eingeschlafene Hasen. Der Köttitröter klopft ans Mikrofon. Beide schrecken hoch und fangen sofort an zu klatschen. Das dürfte Ottah nicht gefallen.','Ottah: Mein Auftritt läuft noch!','Wir haben es gehört. Oft genug.'],
   act1:['Hasenbein flüchtet von der Bühne. Sein metallener Ersatz dreht die Verstärker auf und spielt los. Der Köttitröter verzieht das Gesicht. Sogar eine Motte fliegt gegen den Ausschalter. Cyber-Hasenbein bemerkt nichts davon und setzt zum nächsten schiefen Ton an.','Cyber-Hasenbein: Dieser Ton ist exakt berechnet.','Dann ist dein Taschenrechner kaputt.'],
   act2:['Im Orchesterwerk ist endlich Ruhe. Dann kommt Karnil. Er trägt das goldene Mundstück an einer Kette und schlägt mit zwei Felsbrocken auf den Boden. Er möchte mitspielen. Der Köttitröter hört vier Schläge lang zu und nimmt ihm dann lieber die Steine weg.','Karnil: ICH HALTE DEN TAKT!','Du hältst zwei Steine. Das ist noch nicht dasselbe.'],
   ottah:['Ottah hockt auf dem Bühnenmonitor. Neben ihm hat Pafti gerade das Stromkabel gezogen. Beide grinsen, als der Köttitröter die Trompete hebt. Er wartet einen Moment, damit sie selbst draufkommen. Sie kommen nicht drauf. Na gut. Dann eben mit Vorführung.','Ottah: Ohne Strom spielst du gar nichts!','Hast du schon mal eine Trompete aufgeladen?'],
   pafti:['Karnil ist fast umgefallen. Pafti findet das offenbar zu früh und heilt ihn um ein Viertel seines maximalen Lebens. Der Köttitröter hält mitten im Ton an. Aus dem Publikum kommt ein einzelnes, sehr deutliches „Och nö“. Er nickt und holt noch einmal Luft.','Pafti: Zugabe!','Du räumst nachher die Stühle weg.']
  }
 };
 const celebrations={
  snickers:'Snickers sitzt wieder am Gartentisch. Tee kalt, Teller dreckig, Nuss heil. Er wischt sie am Ärmel ab und beißt hinein. Hinter dem Zaun fragt Hasenbein, ob sie wenigstens geschmeckt hat. Snickers kaut erst in Ruhe fertig. „Ja.“ Den Rest bekommt der General nicht zu hören.',
  raffzahn:'Der Käsekompass hängt wieder an Raffzahns Gürtel. Er führt ihn direkt nach Hause, am Vorratsschrank vorbei und noch einmal zurück. Raffzahn nimmt das als Empfehlung. Beim Essen zeichnet er die neuen Tunnel ein. Hasenbeins Versteck bekommt ein kleines Kreuz. Für später.',
  krustenbraten:'Kornelius hängt das Rezept zurück an seinen Platz. Der Braten ist dunkel geworden, aber unter der Kruste noch saftig. Sogar die besiegten Hasen bekommen eine Scheibe. Als einer nach Ketchup fragt, wird es kurz still. „Draußen“, sagt Kornelius und zeigt mit der Pfanne zur Tür.',
  slanny:'Das Tor ist offen. Ein paar Hasen gehen nach Hause, die anderen setzen sich ins Gras. Slanny steckt sein Abzeichen an und legt die Füße hoch. Einer fragt, wer jetzt die Befehle gibt. „Keiner.“ Der Hase überlegt kurz. Dann legt er ebenfalls die Füße hoch.',
  koettitroeter:'Das goldene Mundstück sitzt wieder. Der Köttitröter zählt ein, und diesmal bleiben alle bis zum letzten Ton. Karnil darf den Takt klopfen, allerdings nur mit zwei Löffeln. Hasenbein sitzt ganz hinten. Seine Brötchen hat er diesmal zum Essen mitgebracht.'
 };
 const failures={snickers:'Snickers sitzt mit dem Hintern im Beet. Die Kanone qualmt. Er pustet Erde aus dem Lauf, schaut zum Zaun und murmelt: „Das erzählen wir keinem.“ Hinter ihm hustet ein Hase. Mist.',raffzahn:'Raffzahn verschwindet im nächsten Gully. Ein guter Rückzug gehört zum Beruf. Dass er dabei mit dem Hintern am Deckel hängenbleibt, kommt nicht in den Bericht.',krustenbraten:'Kornelius sammelt seine Pfanne auf. Die Delle ist neu. „Kann man noch drin braten“, brummt er. Dann dreht er sie um. „Auf der anderen Seite jedenfalls.“',slanny:'Slanny zieht sich über den Zaun zurück. Die Möhrenklinge kommt eine Sekunde später hinterher und bleibt im Pfosten stecken. Er zieht sie heraus. Den eleganten Abgang übt er beim nächsten Mal.',koettitroeter:'Ein schiefer Ton, dann liegt der Köttitröter im Gras. Er hebt einen Finger. „Pause.“ Niemand widerspricht. Selbst Hasenbein braucht gerade einen Moment für seine Ohren.'};
 const quips={snickers:['Nächstes Mal fragst du einfach nach einer Nuss.','Ich wollte heute eigentlich nur im Garten sitzen.','So. Und jetzt lasst mich essen.'],raffzahn:['Der Ausgang ist da hinten. Für dich wird es eng.','Da war die Falle. Hatte ich gesagt.','Ich nehme den Käse. Du nimmst dir eine Pause.'],krustenbraten:['Die Pfanne spüle ich heute nicht mehr.','Und jetzt raus aus meiner Küche.','Das war die Vorspeise.'],slanny:['Abtreten. Das war mein letzter Befehl.','Die Klinge kommt zurück. Du besser nicht.','Ich hab gesagt, ich mache da nicht mehr mit.'],koettitroeter:['Du bist ja ganz still geworden.','Das war erst der Soundcheck.','Den nächsten Ton spiele ich für deine Nachbarn.']};
 function apply(stories){
  stories.snickers={relic:'Haselnuss',dance:'DEN SCHNIEDEL-PILLY-PILLY',danceQuotes:['Nuss gerettet! Platz für den Schniedel-Pilly-Pilly!','Die Pfoten wollen noch nicht nach Hause. Schniedel-Pilly-Pilly!','Kanone abstellen. Hüfte loslassen. Schniedel-Pilly-Pilly!'],victory:['DIE NUSS IST WIEDER ZU HAUSE.','','','']};
  const titles={intro:'DAS WAR MEINE NUSS.',plus:'DU SCHON WIEDER.',plus2:'WER HAT DIE SAHNE?',act1:'ES GIBT NOCH EINEN?',act2:'DIE NUSS BLEIBT HIER.',ottah:'ERWISCHT.',pafti:'EY, DAS ZÄHLT NICHT!'};
  for(const [id,parts]of Object.entries(additions)){
   const story=stories[id];for(const [part,[copy,,quote]]of Object.entries(parts))story[part]=[story[part]?.[0]||titles[part],copy,quote];
   story.quotes=quips[id];story.defeat=failures[id];story.victory=[story.victory[0],...Array.from({length:3},()=>celebrations[id])];
  }
 }
 window.PixelNarrative={apply,additions,celebrations,failures};
})();
